name: Codecov
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Code Coverage
    env:
      JUPYTER_PLATFORM_DIRS: 1 # required to prevent deprecation warning
      UR_GIT_URL: ${{ secrets.UR_GIT_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with: { python-version: 3.12 }
      - name: Install urnc with dev dependencies
        run: python -m pip install .[dev]
      - name: Print tool versions
        run: python --version && pip show pytest
      - name: Run test suite
        run: python -m pytest --cov=urnc --junitxml=junit.xml
      - name: Show junit.xml content
        run: cat junit.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with: { token: "${{ secrets.CODECOV_TOKEN }}" }
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with: { token: "${{ secrets.CODECOV_TOKEN }}" }